ALTER TABLE wm_teams ADD COLUMN IF NOT EXISTS espn_code  VARCHAR(8);
ALTER TABLE wm_teams ADD COLUMN IF NOT EXISTS iso_code   VARCHAR(8);
ALTER TABLE wm_teams ADD COLUMN IF NOT EXISTS emoji_flag VARCHAR(16);
